export const sampleTemplates: TemplateData[] = [
  // Website Builders
  {
    id: 'website-builders',
    name: 'Website Builders',
    criteria: [
      {
        id: 'id-pricing',
        title: 'Pricing',
        description:
          'Monthly cost for standard usage, including hosting and core features.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-ease-of-use',
        title: 'Ease of Use',
        description: 'How beginner-friendly and intuitive the platform is.',
        icon: 'i-mdi-hand-pointing-up',
        type: 'percentage',
        weight: 0,
      },
      {
        id: 'id-design',
        title: 'Design & Templates',
        description: 'Variety and quality of design templates and customization options.',
        icon: 'i-mdi-palette',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-ecommerce',
        title: 'E-Commerce Support',
        description: 'Built-in features and flexibility for selling products online.',
        icon: 'i-mdi-cart',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-seo',
        title: 'SEO Features',
        description: 'Built-in support for SEO best practices.',
        icon: 'i-mdi-google',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-speed',
        title: 'Site Speed & Performance',
        description: 'How well websites built with this tool perform (speed, uptime).',
        icon: 'i-mdi-speedometer',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-flexibility',
        title: 'Design Flexibility',
        description: 'Level of control over layout, styles, and code.',
        icon: 'i-mdi-code-braces',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-support',
        title: 'Customer Support',
        description: 'Availability and quality of customer support.',
        icon: 'i-mdi-headset',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [
      {
        id: 'wix',
        label: 'Wix',
        image: 'https://logo.clearbit.com/wix.com',
        values: {
          'id-pricing': 16,
          'id-ease-of-use': 90,
          'id-design': 8,
          'id-ecommerce': 6,
          'id-seo': 6,
          'id-speed': 6,
          'id-flexibility': 6,
          'id-support': 8,
        },
      },
      {
        id: 'squarespace',
        label: 'Squarespace',
        image: 'https://logo.clearbit.com/squarespace.com',
        values: {
          'id-pricing': 23,
          'id-ease-of-use': 85,
          'id-design': 10,
          'id-ecommerce': 8,
          'id-seo': 8,
          'id-speed': 8,
          'id-flexibility': 6,
          'id-support': 6,
        },
      },
      {
        id: 'shopify',
        label: 'Shopify',
        image: 'https://logo.clearbit.com/shopify.com',
        values: {
          'id-pricing': 29,
          'id-ease-of-use': 80,
          'id-design': 6,
          'id-ecommerce': 10,
          'id-seo': 8,
          'id-speed': 8,
          'id-flexibility': 4,
          'id-support': 8,
        },
      },
      {
        id: 'wordpress',
        label: 'WordPress',
        image: 'https://logo.clearbit.com/wordpress.org',
        values: {
          'id-pricing': 5,
          'id-ease-of-use': 60,
          'id-design': 8,
          'id-ecommerce': 8,
          'id-seo': 10,
          'id-speed': 6,
          'id-flexibility': 10,
          'id-support': 4,
        },
      },
      {
        id: 'webflow',
        label: 'Webflow',
        image: 'https://logo.clearbit.com/webflow.com',
        values: {
          'id-pricing': 18,
          'id-ease-of-use': 70,
          'id-design': 10,
          'id-ecommerce': 6,
          'id-seo': 10,
          'id-speed': 10,
          'id-flexibility': 10,
          'id-support': 6,
        },
      },
      {
        id: 'custom-dev-headless',
        label: 'Custom Dev',
        image: 'https://svgl.app/library/vscode.svg',
        values: {
          'id-pricing': 100,
          'id-ease-of-use': 50,
          'id-design': 10,
          'id-ecommerce': 10,
          'id-seo': 10,
          'id-speed': 10,
          'id-flexibility': 10,
          'id-support': 5,
        },
      },
    ],
  },
  // Home Hunting
  {
    id: 'house-hunting',
    name: 'House / Apartment Hunting',
    criteria: [
      {
        id: 'id-cost',
        title: 'Monthly Rent / Mortgage',
        description: 'Total monthly cost including rent/mortgage and essential fees.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-commute',
        title: 'Commute Time',
        description: 'Average one-way commute time to work/school.',
        icon: 'i-mdi-car-clock',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-space',
        title: 'Living Space (sqft)',
        description: 'Total square footage of usable living area.',
        icon: 'i-mdi-ruler-square',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-safety',
        title: 'Neighborhood Safety',
        description: 'Perceived safety of the neighborhood (crime, lighting, etc).',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-amenities',
        title: 'Amenities',
        description: 'Availability of features like parking, gym, laundry, etc.',
        icon: 'i-mdi-dumbbell',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-walkability',
        title: 'Walkability',
        description: 'Ease of walking to stores, transit, parks, etc.',
        icon: 'i-mdi-walk',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-noise',
        title: 'Noise Levels',
        description: 'How quiet the unit is day and night.',
        icon: 'i-mdi-ear-hearing',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [],
  },
  // Top Gyms
  {
    id: 'gyms',
    name: 'Top Gyms',
    criteria: [
      {
        id: 'id-cost',
        title: 'Monthly Membership Cost',
        description: 'Typical monthly fee for individual access.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-hours',
        title: 'Open 24/7',
        description: 'Is the gym open 24 hours a day, 7 days a week?',
        icon: 'i-mdi-clock',
        type: 'boolean',
        weight: 0,
      },
      {
        id: 'id-locations',
        title: 'Location Access',
        description: 'Access to multiple gym locations nationwide.',
        icon: 'i-mdi-map-marker-multiple',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-equipment',
        title: 'Equipment Quality & Variety',
        description: 'Range and condition of cardio and strength equipment.',
        icon: 'i-mdi-dumbbell',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-classes',
        title: 'Group Classes',
        description: 'Availability and variety of group fitness classes.',
        icon: 'i-mdi-account-group',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-cleanliness',
        title: 'Cleanliness',
        description: 'General cleanliness and maintenance of facilities.',
        icon: 'i-mdi-broom',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-amenities',
        title: 'Amenities',
        description: 'Showers, pool, sauna, child care, etc.',
        icon: 'i-mdi-shower',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-vibe',
        title: 'Atmosphere / Gym Culture',
        description: 'Crowd type, vibe, intimidation factor, staff friendliness.',
        icon: 'i-mdi-emoticon-happy',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [
      {
        id: 'planet-fitness',
        label: 'Planet Fitness',
        image: 'https://logo.clearbit.com/planetfitness.com',
        values: {
          'id-cost': 10,
          'id-hours': true,
          'id-locations': 8,
          'id-equipment': 6,
          'id-classes': 4,
          'id-cleanliness': 7,
          'id-amenities': 4,
          'id-vibe': 9,
        },
      },
      {
        id: 'la-fitness',
        label: 'L.A. Fitness',
        image: 'https://logo.clearbit.com/lafitness.com',
        values: {
          'id-cost': 35,
          'id-hours': false,
          'id-locations': 7,
          'id-equipment': 8,
          'id-classes': 8,
          'id-cleanliness': 6,
          'id-amenities': 7,
          'id-vibe': 6,
        },
      },
      {
        id: '24-hour-fitness',
        label: '24 Hour Fitness',
        image: 'https://logo.clearbit.com/24hourfitness.com',
        values: {
          'id-cost': 40,
          'id-hours': true,
          'id-locations': 6,
          'id-equipment': 7,
          'id-classes': 7,
          'id-cleanliness': 6,
          'id-amenities': 6,
          'id-vibe': 6,
        },
      },
      {
        id: 'golds-gym',
        label: "Gold's Gym",
        image: 'https://logo.clearbit.com/goldsgym.com',
        values: {
          'id-cost': 35,
          'id-hours': false,
          'id-locations': 5,
          'id-equipment': 9,
          'id-classes': 7,
          'id-cleanliness': 7,
          'id-amenities': 7,
          'id-vibe': 8,
        },
      },
      {
        id: 'anytime-fitness',
        label: 'Anytime Fitness',
        image: 'https://logo.clearbit.com/anytimefitness.com',
        values: {
          'id-cost': 40,
          'id-hours': true,
          'id-locations': 9,
          'id-equipment': 6,
          'id-classes': 5,
          'id-cleanliness': 8,
          'id-amenities': 5,
          'id-vibe': 7,
        },
      },
      {
        id: 'equinox',
        label: 'Equinox Fitness',
        image: 'https://logo.clearbit.com/equinox.com',
        values: {
          'id-cost': 200,
          'id-hours': false,
          'id-locations': 4,
          'id-equipment': 9,
          'id-classes': 10,
          'id-cleanliness': 10,
          'id-amenities': 10,
          'id-vibe': 9,
        },
      },
      {
        id: 'lifetime-fitness',
        label: 'Lifetime Fitness',
        image: 'https://logo.clearbit.com/lifetimefitness.com',
        values: {
          'id-cost': 150,
          'id-hours': false,
          'id-locations': 5,
          'id-equipment': 9,
          'id-classes': 9,
          'id-cleanliness': 9,
          'id-amenities': 10,
          'id-vibe': 8,
        },
      },
      {
        id: 'crunch-fitness',
        label: 'Crunch Fitness',
        image: 'https://logo.clearbit.com/crunch.com',
        values: {
          'id-cost': 30,
          'id-hours': false,
          'id-locations': 6,
          'id-equipment': 7,
          'id-classes': 7,
          'id-cleanliness': 6,
          'id-amenities': 6,
          'id-vibe': 8,
        },
      },
    ],
  },
  // Car Hunting
  {
    id: 'car-hunting',
    name: 'Car Hunting',
    criteria: [
      {
        id: 'id-price',
        title: 'Price',
        description: 'The listed price of the car or total cost after taxes/fees.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-mileage',
        title: 'Mileage',
        description: 'Total miles driven (for used cars). Lower is usually better.',
        icon: 'i-mdi-counter',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-fuel',
        title: 'Fuel Efficiency',
        description: 'Miles per gallon (MPG) or equivalent. Higher is better.',
        icon: 'i-mdi-gas-station',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-reliability',
        title: 'Reliability',
        description: 'Expected maintenance needs and breakdown frequency.',
        icon: 'i-mdi-wrench',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-safety',
        title: 'Safety Rating',
        description: 'Crash test performance, safety tech, and ratings.',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-features',
        title: 'Features & Tech',
        description: 'Interior features like navigation, Bluetooth, camera, etc.',
        icon: 'i-mdi-monitor-dashboard',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-insurance',
        title: 'Estimated Insurance Cost',
        description: 'Monthly insurance estimate for your location and profile.',
        icon: 'i-mdi-shield-car',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-resale',
        title: 'Resale Value',
        description: 'Expected future value retention over time.',
        icon: 'i-mdi-cash-refund',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [],
  },
  // House Plants
  {
    id: 'house-plants',
    name: 'House Plants',
    criteria: [
      {
        id: 'id-look',
        title: 'Aesthetic Appeal',
        description: 'Visual appearance, leaf structure, and overall beauty.',
        icon: 'i-mdi-flower',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-size',
        title: 'Mature Size',
        description:
          'Typical size at maturity. Smaller plants may be better for tight spaces.',
        icon: 'i-mdi-ruler',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-ease',
        title: 'Ease of Care',
        description: 'How beginner-friendly and forgiving the plant is.',
        icon: 'i-mdi-thumb-up',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-light',
        title: 'Light Requirements',
        description: 'Amount of natural light the plant needs to thrive.',
        icon: 'i-mdi-white-balance-sunny',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-water',
        title: 'Watering Frequency',
        description: 'How often the plant needs to be watered. Lower is easier.',
        icon: 'i-mdi-water',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-pet-safe',
        title: 'Pet-Safe',
        description: 'Non-toxic to cats and dogs.',
        icon: 'i-mdi-paw',
        type: 'boolean',
        weight: 0,
      },
      {
        id: 'id-growth',
        title: 'Growth Rate',
        description: 'How quickly the plant grows over time.',
        icon: 'i-mdi-chart-line',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [],
  },
  // Shoes Comparison
  {
    id: 'shoes-comparison',
    name: 'Shoes',
    criteria: [
      {
        id: 'id-price',
        title: 'Price',
        description: 'Retail price of the shoes.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 0,
      },
      {
        id: 'id-comfort',
        title: 'Comfort',
        description: 'Cushioning, support, and all-day wear feel.',
        icon: 'i-mdi-sofa',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-style',
        title: 'Style',
        description: 'Visual appeal and fit for your fashion preferences.',
        icon: 'i-mdi-hanger',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-durability',
        title: 'Durability',
        description: 'How well the shoes hold up over time with regular use.',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-versatility',
        title: 'Versatility',
        description: 'Suitability for multiple outfits or activities.',
        icon: 'i-mdi-sync',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-weight',
        title: 'Weight',
        description: 'How lightweight the shoes feel while worn.',
        icon: 'i-mdi-weight',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-breathability',
        title: 'Breathability',
        description: 'Ventilation and airflow during wear.',
        icon: 'i-mdi-wind-turbine',
        type: 'scale-rating',
        weight: 0,
      },
      {
        id: 'id-sustainability',
        title: 'Sustainability',
        description: 'Eco-friendliness of materials and production.',
        icon: 'i-mdi-leaf',
        type: 'scale-rating',
        weight: 0,
      },
    ],
    choices: [],
  },
];
