export const sampleTemplates: TemplateData[] = [
  // Website Builders
  {
    id: 'website-builder-platforms',
    name: 'Website Builder Platforms',
    criteria: [
      {
        id: 'price',
        title: 'Price',
        description: 'Average monthly plan cost',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'ease-of-use',
        title: 'Ease of Use',
        description: 'Intuitiveness for beginners',
        icon: 'i-mdi-hand-pointing-up',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'customizability',
        title: 'Customizability',
        description: 'Flexibility of design, layouts & code access',
        icon: 'i-mdi-cog',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'template-variety',
        title: 'Template Variety',
        description: 'Number & quality of ready-made themes',
        icon: 'i-mdi-grid',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'seo-features',
        title: 'SEO Features',
        description: 'Built-in SEO tools and configurability',
        icon: 'i-mdi-google',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'plugin-ecosystem',
        title: 'Plugin/Extension Ecosystem',
        description: 'Quantity & quality of third-party integrations',
        icon: 'i-mdi-puzzle',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'performance-uptime',
        title: 'Performance/Uptime',
        description: 'Service uptime SLA and real-world reliability',
        icon: 'i-mdi-server',
        type: 'percentage',
        weight: 1,
      },
      {
        id: 'ecommerce-support',
        title: 'E-commerce Support',
        description: 'Native shopping-cart, payments & products',
        icon: 'i-mdi-cart',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'hosting-included',
        title: 'Hosting Included',
        description: 'Is hosting part of the package?',
        icon: 'i-mdi-cloud',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'customer-support-quality',
        title: 'Customer Support Quality',
        description: 'Responsiveness & helpfulness (1–10)',
        icon: 'i-mdi-headset',
        type: 'scale-rating',
        weight: 1,
      },
    ],
    choices: [
      {
        id: 'squarespace',
        label: 'Squarespace',
        image: 'https://logo.clearbit.com/squarespace.com',
        url: 'https://www.squarespace.com',
        values: {
          price: 20,
          'ease-of-use': 8,
          customizability: 7,
          'template-variety': 8,
          'seo-features': 7,
          'plugin-ecosystem': 6,
          'performance-uptime': 99.9,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 7,
        },
      },
      {
        id: 'wix',
        label: 'Wix',
        image: 'https://logo.clearbit.com/wix.com',
        url: 'https://www.wix.com',
        values: {
          price: 14,
          'ease-of-use': 9,
          customizability: 6,
          'template-variety': 7,
          'seo-features': 6,
          'plugin-ecosystem': 7,
          'performance-uptime': 99.9,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 8,
        },
      },
      {
        id: 'hostinger',
        label: 'Hostinger',
        image: 'https://logo.clearbit.com/hostinger.com',
        url: 'https://www.hostinger.com',
        values: {
          price: 5,
          'ease-of-use': 7,
          customizability: 5,
          'template-variety': 6,
          'seo-features': 5,
          'plugin-ecosystem': 4,
          'performance-uptime': 99.5,
          'ecommerce-support': false,
          'hosting-included': true,
          'customer-support-quality': 7,
        },
      },
      {
        id: 'godaddy',
        label: 'GoDaddy',
        image: 'https://logo.clearbit.com/godaddy.com',
        url: 'https://www.godaddy.com',
        values: {
          price: 9,
          'ease-of-use': 7,
          customizability: 5,
          'template-variety': 6,
          'seo-features': 4,
          'plugin-ecosystem': 4,
          'performance-uptime': 99.8,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 6,
        },
      },
      {
        id: 'canva',
        label: 'Canva',
        image: 'https://logo.clearbit.com/canva.com',
        url: 'https://www.canva.com',
        values: {
          price: 12,
          'ease-of-use': 10,
          customizability: 4,
          'template-variety': 9,
          'seo-features': 3,
          'plugin-ecosystem': 2,
          'performance-uptime': 99.9,
          'ecommerce-support': false,
          'hosting-included': true,
          'customer-support-quality': 6,
        },
      },
      {
        id: 'webflow',
        label: 'Webflow',
        image: 'https://logo.clearbit.com/webflow.com',
        url: 'https://www.webflow.com',
        values: {
          price: 20,
          'ease-of-use': 6,
          customizability: 9,
          'template-variety': 7,
          'seo-features': 8,
          'plugin-ecosystem': 5,
          'performance-uptime': 99.99,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 7,
        },
      },
      {
        id: 'carrd',
        label: 'Carrd',
        image: 'https://logo.clearbit.com/carrd.co',
        url: 'https://www.carrd.co',
        values: {
          price: 9,
          'ease-of-use': 9,
          customizability: 5,
          'template-variety': 6,
          'seo-features': 3,
          'plugin-ecosystem': 2,
          'performance-uptime': 99.9,
          'ecommerce-support': false,
          'hosting-included': true,
          'customer-support-quality': 6,
        },
      },
      {
        id: 'wordpress',
        label: 'WordPress.com',
        image: 'https://logo.clearbit.com/wordpress.org',
        url: 'https://www.wordpress.com',
        values: {
          price: 8,
          'ease-of-use': 5,
          customizability: 9,
          'template-variety': 8,
          'seo-features': 8,
          'plugin-ecosystem': 10,
          'performance-uptime': 99.9,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 7,
        },
      },
      {
        id: 'framer',
        label: 'Framer',
        image: 'https://logo.clearbit.com/framer.com',
        url: 'https://www.framer.com',
        values: {
          price: 15,
          'ease-of-use': 7,
          customizability: 7,
          'template-variety': 7,
          'seo-features': 7,
          'plugin-ecosystem': 4,
          'performance-uptime': 99.9,
          'ecommerce-support': false,
          'hosting-included': true,
          'customer-support-quality': 7,
        },
      },
      {
        id: 'durable',
        label: 'Durable',
        image: 'https://logo.clearbit.com/durable.co',
        url: 'https://www.durable.co',
        values: {
          price: 27,
          'ease-of-use': 8,
          customizability: 4,
          'template-variety': 5,
          'seo-features': 3,
          'plugin-ecosystem': 2,
          'performance-uptime': 99.9,
          'ecommerce-support': false,
          'hosting-included': true,
          'customer-support-quality': 5,
        },
      },
      {
        id: 'shopify',
        label: 'Shopify',
        image: 'https://logo.clearbit.com/shopify.com',
        url: 'https://www.shopify.com',
        values: {
          price: 29,
          'ease-of-use': 8,
          customizability: 7,
          'template-variety': 8,
          'seo-features': 7,
          'plugin-ecosystem': 9,
          'performance-uptime': 99.99,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 8,
        },
      },
      {
        id: 'hire-dev',
        label: 'Hire a Developer',
        image: 'https://img.icons8.com/ios-filled/50/source-code.png',
        values: {
          price: 60,
          'ease-of-use': 7,
          customizability: 10,
          'template-variety': 0,
          'seo-features': 9,
          'plugin-ecosystem': 10,
          'performance-uptime': 99.99,
          'ecommerce-support': true,
          'hosting-included': true,
          'customer-support-quality': 10,
        },
      },
    ],
  },
  // Home Hunting
  {
    id: 'house-hunting',
    name: 'House / Apartment Hunting',
    criteria: [
      {
        id: 'id-cost',
        title: 'Monthly Rent / Mortgage',
        description: 'Total monthly cost including rent/mortgage and essential fees.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-commute',
        title: 'Commute Time',
        description: 'Average one-way commute time to work/school.',
        icon: 'i-mdi-car-clock',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-space',
        title: 'Living Space (sqft)',
        description: 'Total square footage of usable living area.',
        icon: 'i-mdi-ruler-square',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-safety',
        title: 'Neighborhood Safety',
        description: 'Perceived safety of the neighborhood (crime, lighting, etc).',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-amenities',
        title: 'Amenities',
        description: 'Availability of features like parking, gym, laundry, etc.',
        icon: 'i-mdi-dumbbell',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-walkability',
        title: 'Walkability',
        description: 'Ease of walking to stores, transit, parks, etc.',
        icon: 'i-mdi-walk',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-noise',
        title: 'Noise Levels',
        description: 'How quiet the unit is day and night.',
        icon: 'i-mdi-ear-hearing',
        type: 'scale-rating',
        weight: 1,
      },
    ],
    choices: [],
  },
  // Top Gyms
  {
    id: 'gyms',
    name: 'Top Gyms',
    criteria: [
      {
        id: 'id-cost',
        title: 'Monthly Membership Cost',
        description: 'Typical monthly fee for individual access.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-hours',
        title: 'Open 24/7',
        description: 'Is the gym open 24 hours a day, 7 days a week?',
        icon: 'i-mdi-clock',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'id-locations',
        title: 'Location Access',
        description: 'Access to multiple gym locations nationwide.',
        icon: 'i-mdi-map-marker-multiple',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-equipment',
        title: 'Equipment Quality & Variety',
        description: 'Range and condition of cardio and strength equipment.',
        icon: 'i-mdi-dumbbell',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-classes',
        title: 'Group Classes',
        description: 'Availability and variety of group fitness classes.',
        icon: 'i-mdi-account-group',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-cleanliness',
        title: 'Cleanliness',
        description: 'General cleanliness and maintenance of facilities.',
        icon: 'i-mdi-broom',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-amenities',
        title: 'Amenities',
        description: 'Showers, pool, sauna, child care, etc.',
        icon: 'i-mdi-shower',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-vibe',
        title: 'Atmosphere / Gym Culture',
        description: 'Crowd type, vibe, intimidation factor, staff friendliness.',
        icon: 'i-mdi-emoticon-happy',
        type: 'scale-rating',
        weight: 1,
      },
    ],
    choices: [
      {
        id: 'planet-fitness',
        label: 'Planet Fitness',
        image: 'https://logo.clearbit.com/planetfitness.com',
        values: {
          'id-cost': 10,
          'id-hours': true,
          'id-locations': 8,
          'id-equipment': 6,
          'id-classes': 4,
          'id-cleanliness': 7,
          'id-amenities': 4,
          'id-vibe': 9,
        },
      },
      {
        id: 'la-fitness',
        label: 'L.A. Fitness',
        image: 'https://logo.clearbit.com/lafitness.com',
        values: {
          'id-cost': 35,
          'id-hours': false,
          'id-locations': 7,
          'id-equipment': 8,
          'id-classes': 8,
          'id-cleanliness': 6,
          'id-amenities': 7,
          'id-vibe': 6,
        },
      },
      {
        id: '24-hour-fitness',
        label: '24 Hour Fitness',
        image: 'https://logo.clearbit.com/24hourfitness.com',
        values: {
          'id-cost': 40,
          'id-hours': true,
          'id-locations': 6,
          'id-equipment': 7,
          'id-classes': 7,
          'id-cleanliness': 6,
          'id-amenities': 6,
          'id-vibe': 6,
        },
      },
      {
        id: 'golds-gym',
        label: "Gold's Gym",
        image: 'https://logo.clearbit.com/goldsgym.com',
        values: {
          'id-cost': 35,
          'id-hours': false,
          'id-locations': 5,
          'id-equipment': 9,
          'id-classes': 7,
          'id-cleanliness': 7,
          'id-amenities': 7,
          'id-vibe': 8,
        },
      },
      {
        id: 'anytime-fitness',
        label: 'Anytime Fitness',
        image: 'https://logo.clearbit.com/anytimefitness.com',
        values: {
          'id-cost': 40,
          'id-hours': true,
          'id-locations': 9,
          'id-equipment': 6,
          'id-classes': 5,
          'id-cleanliness': 8,
          'id-amenities': 5,
          'id-vibe': 7,
        },
      },
      {
        id: 'equinox',
        label: 'Equinox Fitness',
        image: 'https://logo.clearbit.com/equinox.com',
        values: {
          'id-cost': 200,
          'id-hours': false,
          'id-locations': 4,
          'id-equipment': 9,
          'id-classes': 10,
          'id-cleanliness': 10,
          'id-amenities': 10,
          'id-vibe': 9,
        },
      },
      {
        id: 'lifetime-fitness',
        label: 'Lifetime Fitness',
        image: 'https://logo.clearbit.com/lifetimefitness.com',
        values: {
          'id-cost': 150,
          'id-hours': false,
          'id-locations': 5,
          'id-equipment': 9,
          'id-classes': 9,
          'id-cleanliness': 9,
          'id-amenities': 10,
          'id-vibe': 8,
        },
      },
      {
        id: 'crunch-fitness',
        label: 'Crunch Fitness',
        image: 'https://logo.clearbit.com/crunch.com',
        values: {
          'id-cost': 30,
          'id-hours': false,
          'id-locations': 6,
          'id-equipment': 7,
          'id-classes': 7,
          'id-cleanliness': 6,
          'id-amenities': 6,
          'id-vibe': 8,
        },
      },
    ],
  },
  // Car Hunting
  {
    id: 'car-hunting',
    name: 'Car Hunting',
    criteria: [
      {
        id: 'id-price',
        title: 'Price',
        description: 'The listed price of the car or total cost after taxes/fees.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-mileage',
        title: 'Mileage',
        description: 'Total miles driven (for used cars). Lower is usually better.',
        icon: 'i-mdi-counter',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-fuel',
        title: 'Fuel Efficiency',
        description: 'Miles per gallon (MPG) or equivalent. Higher is better.',
        icon: 'i-mdi-gas-station',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-reliability',
        title: 'Reliability',
        description: 'Expected maintenance needs and breakdown frequency.',
        icon: 'i-mdi-wrench',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-safety',
        title: 'Safety Rating',
        description: 'Crash test performance, safety tech, and ratings.',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-features',
        title: 'Features & Tech',
        description: 'Interior features like navigation, Bluetooth, camera, etc.',
        icon: 'i-mdi-monitor-dashboard',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-insurance',
        title: 'Estimated Insurance Cost',
        description: 'Monthly insurance estimate for your location and profile.',
        icon: 'i-mdi-shield-car',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-resale',
        title: 'Resale Value',
        description: 'Expected future value retention over time.',
        icon: 'i-mdi-cash-refund',
        type: 'scale-rating',
        weight: 1,
      },
    ],
    choices: [],
  },
  // House Plants
  {
    id: 'house-plants',
    name: 'House Plants',
    criteria: [
      {
        id: 'id-look',
        title: 'Aesthetic Appeal',
        description: 'Visual appearance, leaf structure, and overall beauty.',
        icon: 'i-mdi-flower',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-size',
        title: 'Mature Size',
        description:
          'Typical size at maturity. Smaller plants may be better for tight spaces.',
        icon: 'i-mdi-ruler',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-ease',
        title: 'Ease of Care',
        description: 'How beginner-friendly and forgiving the plant is.',
        icon: 'i-mdi-thumb-up',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-light',
        title: 'Light Requirements',
        description: 'Amount of natural light the plant needs to thrive.',
        icon: 'i-mdi-white-balance-sunny',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-water',
        title: 'Watering Frequency',
        description: 'How often the plant needs to be watered. Lower is easier.',
        icon: 'i-mdi-water',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-pet-safe',
        title: 'Pet-Safe',
        description: 'Non-toxic to cats and dogs.',
        icon: 'i-mdi-paw',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'id-growth',
        title: 'Growth Rate',
        description: 'How quickly the plant grows over time.',
        icon: 'i-mdi-chart-line',
        type: 'scale-rating',
        weight: 1,
      },
    ],
    choices: [],
  },
  // Shoes Comparison
  {
    id: 'shoes',
    name: 'Shoes',
    criteria: [
      {
        id: 'id-price',
        title: 'Price',
        description: 'MSRP or current retail price.',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'id-comfort',
        title: 'Comfort',
        description: 'Overall underfoot and upper feel.',
        icon: 'i-mdi-sofa',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-durability',
        title: 'Durability',
        description: 'Outsole, upper, and heel wear resistance.',
        icon: 'i-mdi-shield-check',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-breathability',
        title: 'Breathability',
        description: 'Ventilation and airflow during wear.',
        icon: 'i-mdi-weather-windy',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-weight-feel',
        title: 'Weight (Feel)',
        description: 'Subjective sense of lightness during runs.',
        icon: 'i-mdi-weight',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-fit-accuracy',
        title: 'Fit (Accuracy)',
        description: 'True-to-size fit and sizing consistency.',
        icon: 'i-mdi-ruler',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-arch-support',
        title: 'Arch Support',
        description: 'Level of arch support; neutral ≈ 5.',
        icon: 'i-mdi-arch',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'id-cold-drop',
        title: 'Cold Performance Drop',
        description: 'Percentage performance drop in cold conditions.',
        icon: 'i-mdi-snowflake',
        type: 'percentage',
        weight: 1,
      },
      {
        id: 'id-rocker',
        title: 'Rocker Design',
        description: 'Whether the shoe uses a rocker-style sole.',
        icon: 'i-mdi-gesture-swipe',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'id-orthotic',
        title: 'Orthotic Friendly',
        description: 'Supports orthotics (removable insole + volume).',
        icon: 'i-mdi-shoe-print',
        type: 'boolean',
        weight: 1,
      },
    ],
    choices: [],
  },
  {
    id: 'headless-cms-comparison',
    name: 'Headless CMS Platform Comparison',
    criteria: [
      {
        id: 'price',
        title: 'Price',
        description: 'Monthly cost for typical production usage',
        icon: 'i-mdi-currency-usd',
        type: 'cost',
        weight: 1,
      },
      {
        id: 'developer-experience',
        title: 'Developer Experience',
        description: 'Ease of setup, API design, tooling, DX docs',
        icon: 'i-mdi-code-tags',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'content-modeling-flexibility',
        title: 'Content Modeling Flexibility',
        description: 'Schema design, relational support, reusability',
        icon: 'i-mdi-shape',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'api-performance',
        title: 'API Performance',
        description: 'Speed & reliability of GraphQL/REST delivery',
        icon: 'i-mdi-rocket',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'ui-usability-editors',
        title: 'UI Usability for Editors',
        description: 'Editor-friendliness, non-technical UX',
        icon: 'i-mdi-account-box-multiple',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'customization-extensibility',
        title: 'Customization & Extensibility',
        description: 'Ability to add custom logic, plugins, webhooks',
        icon: 'i-mdi-puzzle-plus',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'uptime-availability',
        title: 'Uptime/Availability',
        description: 'SLA or average uptime',
        icon: 'i-mdi-server',
        type: 'percentage',
        weight: 1,
      },
      {
        id: 'role-permission-control',
        title: 'Role & Permission Control',
        description: 'Granularity of roles, access control, multi-user support',
        icon: 'i-mdi-account-key',
        type: 'scale-rating',
        weight: 1,
      },
      {
        id: 'localization-support',
        title: 'Localization Support',
        description: 'Built-in support for multi-language content',
        icon: 'i-mdi-web',
        type: 'boolean',
        weight: 1,
      },
      {
        id: 'self-hosting-available',
        title: 'Self-Hosting Available',
        description: 'Whether the CMS can be hosted independently',
        icon: 'i-mdi-cloud-upload-outline',
        type: 'boolean',
        weight: 1,
      },
    ],
    choices: [
      {
        id: 'nuxt-studio',
        label: 'Nuxt Studio',
        image: 'https://logo.clearbit.com/nuxt.com',
        values: {
          price: 49,
          'developer-experience': 9,
          'content-modeling-flexibility': 7,
          'api-performance': 8,
          'ui-usability-editors': 6,
          'customization-extensibility': 7,
          'uptime-availability': 99.9,
          'role-permission-control': 6,
          'localization-support': false,
          'self-hosting-available': true,
        },
      },
      {
        id: 'storyblok',
        label: 'Storyblok',
        image: 'https://logo.clearbit.com/storyblok.com',
        values: {
          price: 99,
          'developer-experience': 8,
          'content-modeling-flexibility': 8,
          'api-performance': 7,
          'ui-usability-editors': 8,
          'customization-extensibility': 7,
          'uptime-availability': 99.95,
          'role-permission-control': 8,
          'localization-support': true,
          'self-hosting-available': false,
        },
      },
      {
        id: 'prismic',
        label: 'Prismic',
        image: 'https://logo.clearbit.com/prismic.io',
        values: {
          price: 25,
          'developer-experience': 7,
          'content-modeling-flexibility': 7,
          'api-performance': 7,
          'ui-usability-editors': 7,
          'customization-extensibility': 6,
          'uptime-availability': 99.9,
          'role-permission-control': 7,
          'localization-support': true,
          'self-hosting-available': false,
        },
      },
      {
        id: 'sanity',
        label: 'Sanity',
        image: 'https://logo.clearbit.com/sanity.io',
        values: {
          price: 199,
          'developer-experience': 9,
          'content-modeling-flexibility': 9,
          'api-performance': 8,
          'ui-usability-editors': 7,
          'customization-extensibility': 9,
          'uptime-availability': 99.9,
          'role-permission-control': 8,
          'localization-support': true,
          'self-hosting-available': false,
        },
      },
      {
        id: 'strapi',
        label: 'Strapi',
        image: 'https://logo.clearbit.com/strapi.io',
        values: {
          price: 0,
          'developer-experience': 8,
          'content-modeling-flexibility': 8,
          'api-performance': 7,
          'ui-usability-editors': 6,
          'customization-extensibility': 9,
          'uptime-availability': 0, // self-hosted, uptime depends on user
          'role-permission-control': 9,
          'localization-support': true,
          'self-hosting-available': true,
        },
      },
      {
        id: 'contentful',
        label: 'Contentful',
        image: 'https://logo.clearbit.com/contentful.com',
        values: {
          price: 489,
          'developer-experience': 7,
          'content-modeling-flexibility': 7,
          'api-performance': 8,
          'ui-usability-editors': 7,
          'customization-extensibility': 7,
          'uptime-availability': 99.99,
          'role-permission-control': 7,
          'localization-support': true,
          'self-hosting-available': false,
        },
      },
      {
        id: 'directus',
        label: 'Directus',
        image: 'https://logo.clearbit.com/directus.io',
        values: {
          price: 0,
          'developer-experience': 7,
          'content-modeling-flexibility': 8,
          'api-performance': 7,
          'ui-usability-editors': 7,
          'customization-extensibility': 8,
          'uptime-availability': 0, // self-hosted, uptime depends on user
          'role-permission-control': 9,
          'localization-support': true,
          'self-hosting-available': true,
        },
      },
    ],
  },
];
